# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb1168b26f0859dd4f7e6b97afcaf456f1f46b593de1ea8748506d949d106a9bb7e3aad6ceee49d35bd88a38920bb2cddeab94c52977d2f14ccd827f939ab049

test:
  secret_key_base: fb1168b26f0859dd4f7e6b97afcaf456f1f46b593de1ea8748506d949d106a9bb7e3aad6ceee49d35bd88a38920bb2cddeab94c52977d2f14ccd827f939ab049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
